const mongo = require("mongoose");
const Schema = mongo.Schema;
const PlayerStat = new Schema({
    player: {type: Schema.Types.ObjectId, ref: "User"},
    matchId: {type: Schema.Types.ObjectId, ref: "Match"},
    forTeam: {type: Schema.Types.ObjectId, ref: "Team"},
    forTournament: {type: Schema.Types.ObjectId, ref: "Tournament"},
    goals: {type: Number, default: 0},
    assists: {type: Number, default: 0},
    redCards: {type: Number, default: 0},
    yellowCards: {type: Number, default: 0},
    playerMatchRating: {type: Number, default: 1000},
    playerPosition: String,
    playerJerseyNumber: Number,
    playerState: { type: String, default: "Good" },
    shotsOnTarget: { type: Number, default: 0 },
    totalShots: { type: Number, default: 0 },
    passesCompleted: { type: Number, default: 0 },
    passAccuracy: { type: Number, default: 0 },
    tacklesWon: { type: Number, default: 0 },
    interceptions: { type: Number, default: 0 },
    dribblesCompleted: { type: Number, default: 0 },
    distanceCovered: { type: Number, default: 0 },
    minutesPlayed: { type: Number, default: 0 },
    foulsCommitted: { type: Number, default: 0 },
    foulsSuffered: { type: Number, default: 0 },
    duelsWon: { type: Number, default: 0 },
    aerialDuelsWon: { type: Number, default: 0 },
    crossesCompleted: { type: Number, default: 0 },
    offside: { type: Number, default: 0 },
    saves: { type: Number, default: 0 },
    cleanSheets: { type: Number, default: 0 },
    goalsConceded: { type: Number, default: 0 },
    penaltiesSaved: { type: Number, default: 0 },
    penaltyConceded: { type: Number, default: 0 },
    penaltyScored: { type: Number, default: 0 },
    ownGoals: { type: Number, default: 0 },
    substitutionsOn: { type: Number, default: 0 },
    substitutionsOff: { type: Number, default: 0 },
    minutesPerGoal: { type: Number, default: 0 },
    minutesPerAssist: { type: Number, default: 0 },
    minutesPerShot: { type: Number, default: 0 },
    minutesPerPass: { type: Number, default: 0 },
    minutesPerTackle: { type: Number, default: 0 },
    minutesPerInterception: { type: Number, default: 0 },
    minutesPerDribble: { type: Number, default: 0 },
    minutesPerAerialDuel: { type: Number, default: 0 },
    minutesPerCross: { type: Number, default: 0 },
    minutesPerFoul: { type: Number, default: 0 },
    minutesPerFoulSuffered: { type: Number, default: 0 },
    minutesPerDuelWon: { type: Number, default: 0 },
    minutesPerMinutePlayed: { type: Number, default: 0 },
    minutesPerShotOnTarget: { type: Number, default: 0 },
    minutesPerGoalConceded: { type: Number, default: 0 },
    minutesPerSave: { type: Number, default: 0 },
    minutesPerPenaltySaved: { type: Number, default: 0 },


});
module.exports = mongo.model("playerstat", PlayerStat);
